openapi: 3.0.2
info:
    title: Library-API
    version: 1.0.0
    description: '### This is a Swagger UI for our Library API'
paths:
    /users:
        get:
            tags:
                - users
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                List of users:
                                    value: |-
                                        [
                                            {id:1,firstname:"Jeff",lastname:"Bezos",email:"jeffbezos@amazon.com",password:"markzuckerbergsux",username:"bigbezos420",phonenr:"+1 11748794 "},
                                            {id:2,firstname:"Mark",lastname:"Zuckerberg",email:"markzuckerberg@facebook.com",password:"jeffbezossux",username:"markzuckofficial",phonenr:"+1 82543794 "}
                                        ]
                    description: Returns list of users
            summary: Get list of users
            description: Returns list of all users
    /books:
        get:
            tags:
                - books
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/book'
                            examples:
                                All Books:
                                    value:
                                        -
                                            id: 1513
                                            name: Romeo and Juliet
                                        -
                                            id: 2701
                                            name: 'Moby Dick; Or, The Whale'
                                        -
                                            id: 2641
                                            name: A Room with a View
                                        -
                                            id: 145
                                            name: Middlemarch
                                        -
                                            id: 67979
                                            name: 'The Blue Castle: a novel'
                                        -
                                            id: 16389
                                            name: The Enchanted April
                                        -
                                            id: 37106
                                            name: 'Little Women; Or, Meg, Jo, Beth, and Amy'
                                        -
                                            id: 394
                                            name: Cranford
                                        -
                                            id: 6761
                                            name: The Adventures of Ferdinand Count Fathom — Complete
                                        -
                                            id: 2160
                                            name: The Expedition of Humphry Clinker
                                        -
                                            id: 4085
                                            name: The Adventures of Roderick Random
                                        -
                                            id: 1342
                                            name: Pride and Prejudice
                                        -
                                            id: 6593
                                            name: 'History of Tom Jones, a Foundling'
                                        -
                                            id: 1259
                                            name: Twenty years after
                                        -
                                            id: 5197
                                            name: My Life — Volume 1
                                        -
                                            id: 100
                                            name: The Complete Works of William Shakespeare
                                        -
                                            id: 84
                                            name: 'Frankenstein; Or, The Modern Prometheus'
                                        -
                                            id: 11
                                            name: Alice's Adventures in Wonderland
                                        -
                                            id: 1399
                                            name: Anna Karenina
                                        -
                                            id: 345
                                            name: Dracula
                                        -
                                            id: 174
                                            name: The Picture of Dorian Gray
                                        -
                                            id: 25344
                                            name: The Scarlet Letter
                                        -
                                            id: 1661
                                            name: The Adventures of Sherlock Holmes
                                        -
                                            id: 1184
                                            name: The Count of Monte Cristo
                                        -
                                            id: 98
                                            name: A Tale of Two Cities
                                        -
                                            id: 5200
                                            name: Metamorphosis
                                        -
                                            id: 3600
                                            name: Essays of Michel de Montaigne — Complete
                                        -
                                            id: 16328
                                            name: 'Beowulf: An Anglo-Saxon Epic Poem'
                                        -
                                            id: 64317
                                            name: The Great Gatsby
                                        -
                                            id: 6130
                                            name: The Iliad
                                        -
                                            id: 2680
                                            name: Meditations
                                        -
                                            id: 28054
                                            name: The Brothers Karamazov
                    description: Returns array of books
            summary: Get all Books
            description: Returns array of books
        post:
            tags:
                - books
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                type: string
                            examples:
                                Create new Book:
                                    value:
                                        id: 24
                                        createdAt: 2023/09/26
                    description: 'Returns created book id, createdAt'
            summary: Add new Book
            description: 'Returns created book id, createdAt'
    '/users/{id}':
        get:
            tags:
                - details
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                Full details of book:
                                    value: >-
                                        id:1,firstname:"Jeff",lastname:"Bezos",email:"jeffbezos@amazon.com",password:"markzuckerbergsux",username:"bigbezos420",phonenr:"+1
                                        11748794"}
                    description: Returns full details of given id user
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                'User /w+ was not found ':
                                    value:
                                        error: User \w+ was not found in game array.
                    description: User was not found
            operationId: id
            summary: Get details of a user
            description: Returns details of user
        parameters:
            -
                name: id
                in: path
                required: true
    '/books/{id}':
        get:
            tags:
                - books
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/book'
                            examples:
                                Single Book:
                                    value:
                                        id: 1513
                                        name: Romeo and Juliet
                    description: Returns Book by id
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                Not found.:
                                    value:
                                        error: book not found.
                    description: Returns error
            summary: Get one Book
            description: Returns Book by id
        put:
            tags:
                - books
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/book'
                            examples:
                                New Book:
                                    value: "{\r\n    \"id\": 1513,\r\n    \"name\": \"Romeo and Juliet 2\"\r\n},"
                    description: Returns updated Book
                '400':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                Error:
                                    value:
                                        error: Invalid fields provided.
                    description: Returns error
            summary: Update Book by id
            description: Returns updated Book
        parameters:
            -
                name: id
                schema:
                    type: integer
                in: path
                required: true
components:
    schemas:
        error:
            title: Root Type for error
            description: ''
            type: object
            properties:
                error:
                    type: string
            example:
                error: Error message.
        book:
            title: Root Type for book
            description: ''
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                name:
                    type: string
            example:
                id: 1513
                name: Romeo and Juliet
