openapi: 3.0.2
info:
    title: Library-API
    version: 1.0.0
    description: '### This is a Swagger UI for our Library API'
paths:
    /users:
        get:
            tags:
                - users
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                List of users:
                                    value: |-
                                        [
                                            {id:1,firstname:"Jeff",lastname:"Bezos",email:"jeffbezos@amazon.com",password:"markzuckerbergsux",username:"bigbezos420",phonenr:"+1 11748794 "},
                                            {id:2,firstname:"Mark",lastname:"Zuckerberg",email:"markzuckerberg@facebook.com",password:"jeffbezossux",username:"markzuckofficial",phonenr:"+1 82543794 "}
                                        ]
                    description: Returns list of users
            summary: Get list of users
            description: Returns list of all users
    /books:
        get:
            tags:
                - books
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/book'
                            examples:
                                List of books:
                                    value:
                                        -
                                            id: 1
                                            title: Romeo and Juliet
                                            author: William Shakespeare
                                            description: >-
                                                Romeo and Juliet, play by William Shakespeare, written about
                                                1594–96 and first published in an unauthorized quarto in 1597.
                                                An authorized quarto appeared in 1599, substantially longer
                                                and more reliable.
                                            releasedate: '1597'
                                            booklength: 480
                                            language: English
                                            price: 5.99
                                            pdf: '?'
                                        -
                                            id: 2
                                            title: 'Moby Dick; Or, The Whale'
                                            author: Herman Melville
                                            description: >-
                                                Moby-Dick; or, The Whale is an 1851 novel by American writer
                                                Herman Melville. The book is the sailor Ishmael's narrative of
                                                the maniacal quest of Ahab, captain of the whaling ship
                                                Pequod, for vengeance against Moby Dick, the giant white sperm
                                                whale that bit off his leg on the ship's previous voyage.
                                            releasedate: '1851'
                                            booklength: 378
                                            language: English
                                            price: 4.99
                                            pdf: '?'
                                        -
                                            id: 3
                                            title: A Room with a View
                                            author: E. M. Forster
                                            description: Romeo and Juliet
                                            releasedate: '1908'
                                            booklength: 321
                                            language: English
                                            price: 3.99
                                            pdf: '?'
                                        -
                                            id: 4
                                            title: Middlemarch
                                            author: '?'
                                            description: '?'
                                            releasedate: '?'
                                            booklength: '?'
                                            language: '?'
                                            price: '?'
                                            pdf: '?'
                                        -
                                            id: 5
                                            title: 'The Blue Castle: a novel'
                                            author: '?'
                                            description: '?'
                                            releasedate: '?'
                                            booklength: '?'
                                            language: '?'
                                            price: '?'
                                            pdf: '?'
                    description: >-
                        Returns an array of Books (id, title, author, description, releasedate, booklength,
                        language, price)
            summary: Get list of books
            description: Returns an array of Books
        post:
            requestBody:
                description: |-
                    {
                      "title": "Romeo and Juliet",
                      "author": "William Shakespeare",
                      "description": "Romeo and Juliet, play by William Shakespeare, written about 1594–96 and first published in an unauthorized quarto in 1597. An authorized quarto appeared in 1599, substantially longer and more reliable.",
                      "releasedate": "1597",
                      "booklength": 480,
                      "language": "English",
                      "price": 5.99,
                      "pdf": "?"
                    }
                required: true
            tags:
                - books
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                type: string
                            examples:
                                Create new Book:
                                    value:
                                        id: 1
                                        title: Romeo and Juliet
                                        author: William Shakespeare
                                        description: >-
                                            Romeo and Juliet, play by William Shakespeare, written about
                                            1594–96 and first published in an unauthorized quarto in 1597. An
                                            authorized quarto appeared in 1599, substantially longer and more
                                            reliable.
                                        releasedate: '1597'
                                        booklength: 480
                                        language: English
                                        price: 5.99
                    description: >-
                        Returns created Book (id, title, author, description, releasedate, booklength,
                        language, price)
            operationId: /books/create
            summary: Add new Book
            description: Returns created Book
    '/users/{id}':
        get:
            tags:
                - users
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/user'
                            examples:
                                Full details of book:
                                    value:
                                        id: 44
                                        firstname: some text
                                        lastname: some text
                                        email: some text
                                        password: some text
                                        username: some text
                                        phonenr: some text
                    description: Returns full details of given id user
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                'User /w+ was not found ':
                                    value:
                                        error: User \w+ was not found in game array.
                    description: User was not found
            operationId: id
            summary: Get details of a user
            description: Returns details of user
        put:
            requestBody: {}
            tags:
                - users
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                    description: Updates details
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
            summary: Update details of a user
            description: Updates details of user
        delete:
            tags:
                - users
            responses:
                '204':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
            description: Deletes user from database
        parameters:
            -
                name: id
                in: path
                required: true
    '/books/{id}':
        get:
            tags:
                - books
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/book'
                            examples:
                                Book:
                                    value:
                                        id: 1
                                        title: Romeo and Juliet
                                        author: William Shakespeare
                                        description: >-
                                            Romeo and Juliet, play by William Shakespeare, written about
                                            1594–96 and first published in an unauthorized quarto in 1597. An
                                            authorized quarto appeared in 1599, substantially longer and more
                                            reliable.
                                        releasedate: '1597'
                                        booklength: 480
                                        language: English
                                        price: 5.99
                    description: >-
                        Returns book by id (id, title, author, description, releasedate, booklength, language,
                        price)
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                Not found.:
                                    value:
                                        error: book not found.
                    description: Returns error
            summary: Get one book
            description: Returns book by id
        put:
            requestBody:
                description: |-
                    {
                      "title": "Romeo and Juliet2",
                      "author": "William Shakespeare2",
                      "description": "A play by William Shakespeare, written about 1594–96 and first published in an unauthorized quarto in 1597. An authorized quarto appeared in 1599, substantially longer.",
                      "releasedate": "1597",
                      "booklength": 480,
                      "language": "English",
                      "price": 6.95,
                      "pdf": "?"
                    },
                required: true
            tags:
                - books
            responses:
                '200':
                    content:
                        text/xml:
                            examples:
                                Success:
                                    value: '"book updated successfully."'
                    description: OK
            summary: Update book
            description: Updates book by id
        delete:
            tags:
                - books
            responses:
                '204':
                    description: No content
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                Book not found.:
                                    value:
                                        error: book not found.
                    description: Book not found
            summary: Delete book by id
            description: Deletes book using its id
        parameters:
            -
                name: id
                schema:
                    type: integer
                in: path
                required: true
components:
    schemas:
        error:
            title: Root Type for error
            description: ''
            type: object
            properties:
                error:
                    type: string
            example:
                error: Error message.
        user:
            title: Root Type for user
            description: ''
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                firstname:
                    type: string
                lastname:
                    type: string
                email:
                    type: string
                password:
                    type: string
                username:
                    type: string
                phonenr:
                    type: string
            example:
                id: 1
                firstname: Jeff
                lastname: Bezos
                email: jeffbezos@amazon.com
                password: markzuckerbergsux
                username: bigbezos420
                phonenr: +1 11748794
        book:
            title: Root Type for book
            description: book entity
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                title:
                    type: string
                author:
                    type: string
                description:
                    type: string
                releasedate:
                    type: string
                booklength:
                    format: int32
                    type: integer
                language:
                    type: string
                price:
                    format: double
                    type: number
                pdf:
                    type: string
            example:
                id: 1
                title: Romeo and Juliet
                author: William Shakespeare
                description: >-
                    Romeo and Juliet, play by William Shakespeare, written about 1594–96 and first published
                    in an unauthorized quarto in 1597. An authorized quarto appeared in 1599, substantially
                    longer and more reliable.
                releasedate: '1597'
                booklength: 480
                language: English
                price: 5.99
                pdf: '?'
